### ISSUE TITLE
aiohttp-session does not set cache-control headers

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp-session#124]
The aiohttp-session does not set cache-control headers (such as private), to prevent session based content to be cached by intermediate hosts; this could potentally lead to information leakage

**Comment by asvetlov** [comment]
Sorry for late answer but I don't agree.
If a storage implementation saves session data in cookie as not encrypted data malware proxy could grab this sensitive data regardless to `cache-control`.

If the data is encrypted or stored locally on the server -- I see no leakage.

Would you show the scenario where security problem is possible?
