### ISSUE TITLE
Support for cookieless sessions

### ISSUE THREAD

**Issue by machakux** [aio-libs/aiohttp-session#213]
Hi,

I think there are reasonable use cases where people would like to use sessions when using aiohttp without `aiohttp.web` or `cookies` .

For example 
- When using aiohttp/asyncio inside other frameworks and would like to use aiohttp in asynchronous session management
- When developing something like a chatbot in platforms like [messenger platform](https://developers.facebook.com/docs/messenger-platform) where cookies are not supported
- When you want to have some sort of sessions when providing an API consumed by native apps
- ... etc

I know in a lot of cases standard HTTP sessions are used with cookies but since aiohttp is now being used in very diverse environments may be it would be useful to have at least one session storage backend which can fully function without `aiohttp.web.Resquest/Response` objects.

Does this sound reasonable?

I am imagining something like the below ("Cookieless Redis Session Storage")

    import asyncio
    import json
    import uuid

    from aiohttp_session import AbstractStorage, Session

    class RedisCookielessStorage(AbstractStorage):
        """Redis storage"""

        def __init__(self, redis_pool, *, key_prefix="aiohttp_session",
                     domain=None, max_age=None, path='/',
                     secure=None, httponly=True,
                     encoder=json.dumps, decoder=json.loads,
                     key_factory=lambda: uuid.uuid4().hex):
            super().__init__(domain=domain, max_age=max_age, path=path,
                             secure=secure, httponly=httponly)
            self._encoder = encoder
            self._decoder = decoder
            self._key_prefix = key_prefix
            self._key_factory = key_factory
            self._redis = redis_pool

        @property
        def key_prefix(self):
            return self._key_prefix

        @asyncio.coroutine
        def load_session(self, key=None):
            if key is None:
                return Session(None, data=None, new=True, max_age=self.max_age)
            else:
                with (yield from self._redis) as conn:
                    data = yield from conn.get(self.key_prefix + ':' + key)
                    if data is None:
                        return Session(key, data=None, new=True, max_age=self.max_age)
                    data = data.decode('utf-8')
                    try:
                        data = self._decoder(data)
                    except ValueError:
                        data = None
                    return Session(key, data=data, new=False, max_age=self.max_age)

        @asyncio.coroutine
        def save_session(self, session):
            key = session.identity or self._key_factory()
            data = self._encoder(self._get_session_data(session))
            with (yield from self._redis) as conn:
                max_age = session.max_age
                expire = max_age if max_age is not None else 0
                yield from conn.set(self.key_prefix + ':' + key,
                                    data, expire=expire)

Then you can do something like

    redis = await aioredis.create_pool(('localhost', 6379))
    session_storage = RedisCookielessStorage(redis)

    session = await session_storage.load_session('<YOUR_SESSION_KEY>')
     ...
    await session_storage.save_session(session)

**Comment by asvetlov** [comment]
But how it works with `aiohttp_session.get_session(request)`?

**Comment by machakux** [comment]
It won't work with the current `aiohttp_session.get_session` right now because aiohttp_session.get_session requires aiohttp.web.Request object for retriving session key and storage instance .

I think some of possible solutions to this are

 - Modifying `aiohttp_session.get_session` to accept either a request or session key and storage instance
- Creating an independent helper function for getting session instance from session key and storage instance. In this case the new function may also be reused by `aiohttp_session.get_session`
- Using `storage.load_session('<YOUR_SESSION_KEY>')` directly from storage instance to get a session instance

**Comment by asvetlov** [comment]
The key idea for the project is setting up the session storage by `setup()` and getting session by unified `get_session()` call regardless to exact storage implementation.

You can implement own `RedisCookielessStorage` with overriding `load_session(request)` and `save_session(request, response, session)`. Just don't touch cookies.

But using the library without request/response is out of the project mission and looks like leaked abstraction. I see no reason for supporting the feature by the library. But you could make a custom storage on your own, isn't it?

**Comment by machakux** [comment]
Ok ... Creating a custom session storage by deriving from `AbstractStorage` or even by using a  plain python client for redis is not very difficult.

If cookieless sessions or using aiohttp_session with other frameworks aside from `aiohttp.web` is out of project scope I think this issue can be closed.

**Comment by asvetlov** [comment]
The project is called *atiohttp-session* at least, it is intended to work with `aiohttp.web` ;)
