### ISSUE TITLE
Does aiohttp-session use pickle?

### ISSUE THREAD

**Issue by cdunklau** [aio-libs/aiohttp-session#214]
I was considering using this lib until I saw in the docs that it used pickle:

> Note
> Keys and values of session data must be pickleable.

http://aiohttp-session.readthedocs.io/en/latest/reference.html#aiohttp_session.Session.changed

However, I can't seem to find any reference to pickle in the source, it seems like all of the storage backends use json, not pickle. Is this a doc bug? Should it say "json serializable" instead of "picklable"?

**Comment by asvetlov** [comment]
Yes, you are right.
Would you make a Pull Request with doc update?

Pickle is too dangerous, you can serialize a half of the program memory in a moment ;)

**Comment by cdunklau** [comment]
Sure, I'll get on that after work today.

**Comment by asvetlov** [comment]
thanks
