### ISSUE TITLE
Rewrite middleware to use new styled middlewares from aiohttp 2.3

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-session#216]
`@web.middleware` should be used.
The task is trivial, I hope somebody will pick it up.

**Comment by panagiks** [comment]
I'll take a look to the new midleware style and I hope to have it ready by tomorrow :)

**Comment by asvetlov** [comment]
http://aiohttp.readthedocs.io/en/stable/web.html#middlewares

**Comment by asvetlov** [comment]
I believe the doc has enough information.
Otherwise it should be improved ;)

**Comment by panagiks** [comment]
Yeap the docs were on point :+1:
