### ISSUE TITLE
[Redis] Sentinel Pool support

### ISSUE THREAD

**Issue by panagiks** [aio-libs/aiohttp-session#218]
As it seems from [Issue 185](https://github.com/aio-libs/aioredis/issues/185) and [some references in documentation](http://aioredis.readthedocs.io/en/latest/sentinel.html#sentinelpool) aioredis will be adding Sentinel support in V1.0. 
Is it within the project's scope to support both connection pools and sentinel pools? 

If so I'd like to take a swing at implementing this feature once aioredis version that includes the feature is released.

Also should we choose to implement this I can already see tests being a bit tricky (not so much on the python side but more on the 'we will need to have a redis cluster to test against' side), so any leads in that field would be greatly appreciated. 

My initial thought was to completely patch (mock) the class for the Sentinel Pool, but this carries the drawback that our tests will be as accurate as our mock class (i.e. if the mocked class is wrong and the tests are passing).

**Comment by asvetlov** [comment]
+1 for sentinel support.

Regarding to tests: we should run redis in docker like https://github.com/aio-libs/aiopg and https://github.com/wikibusiness/aioelasticsearch do (take a look on fixtures in `./tests/conftest.py`).

Migration to docker might make next steps easier. For cluster we can start multiple docker containers in this way.

**Comment by panagiks** [comment]
From a first few trials I made it seems that Redis Sentinel is supported out of the box (with the current, not yet stabilized Sentinel API of `aioredis`). The following worked for me:

```py
sentinel = await aioredis.create_sentinel([('ip', port)])
pool = sentinel.master_for('service_name')
storage = RedisStorage(pool)
```

This works because `master_for` returns a `ManagedPool` wrapped in an `aioredis.commands.Redis` so the interface remains the same.

I'll make a few more test and hopefully add a demo for Redis Sentinel in a couple days.

I suggest that we don't close this issue until `aioredis` removes the warning that the sentinel API is not yet finalized.

**Comment by asvetlov** [comment]
@popravich could you confirm that @panagiks assumption about sentinel support in aioredis/aiohttp-session is correct?

**Comment by popravich** [comment]
Yes, it is that easy.
The Sentinel client is usable, however it is not well-tested or documented,
so some changes to the API might happen when more tests/docs/features are added to Sentinel client.
