### ISSUE TITLE
Testing data in session

### ISSUE THREAD

**Issue by achernetsky** [aio-libs/aiohttp-session#221]
Hello,

Tell me please, how I get session in test? For example, check `last_visit is not None` from https://github.com/aio-libs/aiohttp-session/blob/master/demo/redis_storage.py ?

```python
async def test_last_visit(client):
    resp = await client.get('/')
    assert resp.status == 200
   # how get session?
```

Thanks

**Comment by asvetlov** [comment]
Are you looking for something like this? https://github.com/aio-libs/aiohttp-session/blob/master/tests/test_redis_storage.py#L74-L88

**Comment by achernetsky** [comment]
@asvetlov, yes, I looked this code, but I can not replace the `handler` https://github.com/aio-libs/aiohttp-session/blob/master/demo/redis_storage.py#L10
That is, I want to test handler, not replace and test.

**Comment by asvetlov** [comment]
Another option is applying a test middleware.
The session is available from it.

**Comment by achernetsky** [comment]
I've been thinking and came up
```python
from aiohttp_session import SESSION_KEY
from aiohttp.test_utils import make_mocked_request   

async def test_last_visit():
    req = make_mocked_request(
        'GET',
        '/',
    )
    request[SESSION_KEY] = {}
    resp = handler(req)
    
    assert resp.status == 200
    assert 'last_visit' in req[SESSION_KEY]
    assert req[SESSION_KEY]['last_visit'] is not None
```

**Comment by asvetlov** [comment]
Yes, it also works

**Comment by asvetlov** [comment]
Let's close the issue
