### ISSUE TITLE
Rewrite tests to use docker

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-session#226]
Like aiopg
We need to use dockerized redis and memcache servers in our tests.
It simplifies local development.

**Comment by panagiks** [comment]
+1 
I can give it a shot in the weekend.

**Comment by jettify** [comment]
Please use `aiodocker` library, some inspiration you may find here:
simple example
https://github.com/aio-libs/aiozipkin/blob/master/tests/docker_fixtures.py
and more complex
https://github.com/aio-libs/aioodbc/blob/master/tests/conftest.py

**Comment by asvetlov** [comment]
Tests recreate a loop every time.
How aiodocker works in this case if it is used session scoped fixture?

**Comment by jettify** [comment]
Loop is session scoped everywhere, in tests too

**Comment by asvetlov** [comment]
> Loop is session scoped everywhere, in tests too

It means tests are not isolated, isn't it?
