### ISSUE TITLE
[Suggestion][middleware] Add flag to silence storage exceptions

### ISSUE THREAD

**Issue by panagiks** [aio-libs/aiohttp-session#228]
Would it be in scope of the project to add the option to silence Exceptions raised during `storage.save_session` that happens [here](https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/__init__.py#L142)?

My reasoning is that if you have a long-running or computationally expensive request that completed successfully you wouldn't want to loose your response (since a raise at that point means that the response will not be available to the upper middleware) if for example a write that renews the last visit value of a user's session fails (insert any other non-essential info stored in a session).

Alternatively could we add a new Exception Class that will have the response as an attribute (so an upper middleware can still access the response)? Or add the attribute to the caught exception and re-raise it?

Also open for any other suggestions as to how the response could be preserved in case a raise occurs during `storage.save_session`.

**Comment by asvetlov** [comment]
Not sure what to do.
Session could store not only `last_visit` value but very sensitive data (like information about logged in user).
Ignorance of the information update could lead to very serious problems.
Thus I think your idea is quite dangerous.
Also I don't remember such functionality in other python frameworks.

**Comment by panagiks** [comment]
Thinking that lead me to the second suggestion. Re-raising a custom error that will contain the response that is returned [here](https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/__init__.py#L127), or even just injecting the response to the caught exception and re-raising it (see example in the end). And while allowing a silencing is not by it self dangerous (if someone knowingly silences it knowing they don't store sensitive info) i understand it can be dangerous if someone silences the errors without understanding what it means.

I too don't have an example of another framework that does it, but I'm raising an example that I have encountered, loosing the response of a long request because a non-essential write failed. And while I can just remove the non-essential write completely I think that providing the option of retaining the response would potentially benefit users in some use cases.

An example of what I thought is something like this (yes blanket except is bad):

```py
try:
    yield from storage.save_session(request, response, session)
except Exception as e:
    e.aiohttp_response = response
    raise e
```

**Comment by asvetlov** [comment]
I don't ready for such change in `aiohttp-session`, at least for now.
You could write a custom storage which wraps `save_session` and does everything what your want.
```
class Wrapper:
     def __init__(self, implementation):
         self._imp = implementation
     async def save_session(self, request, response, session):
         try:
             await self._impl.save_session(request, response, session)
         except  Exception:
             pass
```

**Comment by panagiks** [comment]
Ok, I'll be closing the issue then.

The wrapper approach seems to also be able to solve my issue. Thank you :)
