### ISSUE TITLE
React + Session

### ISSUE THREAD

**Issue by gonardfreeman** [aio-libs/aiohttp-session#232]
Hello guys, how to write cookie session to my react app, when i'm in developing mode? I'm syncing data via proxy.
In ideal I'm need to create session on my react app, because when I'm coping cookie to react and trying to read it on server app response with: "Cannot decrypt cookie value, create a new fresh session".

**Comment by asvetlov** [comment]
Sorry, I don't use React and cannot figure out what is broken.
Could you pin down your problem?

**Comment by gonardfreeman** [comment]
@asvetlov I'm figure out where was problem) when you use create react app and make some GET/POST you need add additional param to your request `credentials: 'include'`, so your fetch will look like this:
```javascript
return fetch(`http://${MAINSITE}/login`, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data),
      credentials: 'include'
    })
```
it will pass cookies via proxy, because with out this there where no cookies in request param of view, so `get_session(request)` cannot read it.
