### ISSUE TITLE
Add the ability set `identity` of session if it is `new`

### ISSUE THREAD

**Issue by achernetsky** [aio-libs/aiohttp-session#236]
Hello,

What do you think about it?

I need set `identity`, which used how `key` in redis,  of session with custom key. And then I need remove session by that `identity` from redis by message from amqp with this `identity`.

Now `identity` [readonly property](https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/__init__.py#L45).

Example code
```python
class LoginView(BaseView):
   async def post(self):
       session = await aiohttp_session.get_session(self.request)
       if session.new:
           session.identity = 'key'
       session['user'] = {...}
```

Thanks.

**Comment by asvetlov** [comment]
The request is controversial.
`session.identity` should be kept readonly but we could `session.set_new_identity()` method.
The method will generate an exception is `not session.new`.

If you need the functionality -- please make a pull request :)
Tests and documentation are required.

**Comment by achernetsky** [comment]
@asvetlov, please, review pull request. Thanks.
