### ISSUE TITLE
Makefile depends on Python 2 with setuptools

### ISSUE THREAD

**Issue by cmcqueen** [aio-libs/aiohttp-session#242]
I'm trying to build aiohttp and aiohttp-session under Yocto. It tries to run `make clean` as part of the build process. `make clean` runs `python setup.py clean`. But that runs Python 2, and that fails because the build system doesn't have Python 2 with `setuptools` installed.

Since aiohttp is Python 3 only, would it make more sense for the `Makefile` to run `python3 make clean` instead, to avoid such unusual Python 2 dependencies?

**Comment by asvetlov** [comment]
Please use virtual environment.
Inside properly installed virtualenv/venv `python` is an alias for `python3`

**Comment by cmcqueen** [comment]
Yocto is a project for creating custom Linux builds, used especially for embedded Linux systems. Python virtualenv is a great workflow for many situations, but isn't really suited for Yocto builds.

But, your answer seems to be the right one in principle anyway, which is the Yocto build system needs to set up an environment in which `python` refers to `python3`.

**Comment by asvetlov** [comment]
The issue appears only on `aiohttp-session` *development*, where you should use virtual environment.
The virtual env is not required for *using* `aiohttp-session`, `pip install aiohttp-session` could be used on system Python too (but virtual envs are very encouraged).

**Comment by cmcqueen** [comment]
Thanks. For Yocto builds, I've set `CLEANBROKEN = "1"` in the `python3-aiohttp-session` bitbake recipe. I think that should be okay.
