### ISSUE TITLE
Other implementations for AbstractStorage.

### ISSUE THREAD

**Issue by alexpantyukhin** [aio-libs/aiohttp-session#277]
Would it be good to make other storages? For example `Mongo` and `CouchDB`. If yes, I would like to implement these. But need to be sure that it could be interesting.

**Comment by asvetlov** [comment]
I think you can make a third-party plugin for such storages without touching `aiohttp-session` itself.
After some period we can consider incorporation this plugin into upstream.

There are too many possible storages for a session, support every new one is a maintenance burden.

**Comment by asvetlov** [comment]
Feel free to update README/ docs to mention your plugin libraries.
It would be nice to have the whole list of plugins in the same place.

**Comment by asvetlov** [comment]
I think the issue could be closed.
