### ISSUE TITLE
Q: uuid4 vs urandom(16) for Redis keys

### ISSUE THREAD

**Issue by jashandeep-sohi** [aio-libs/aiohttp-session#28]
This is more of question than an issue (and maybe not even specific to `aiohttp_session`), but I was wondering why are the keys using `uuid4` when `codecs.encode(urandom(16), 'hex')` would suffice?
Is it just a preference or is there some deeper reason?

**Comment by asvetlov** [comment]
It's just my preference.
uuid4 uses `urandom(16)` internally.

**Comment by jashandeep-sohi** [comment]
Would it be okay if I add a `key_factory` parameter to `RedisStorage`? Default could still be `uuid4`.

**Comment by asvetlov** [comment]
Please do

**Comment by smialy** [comment]
#205

**Comment by smialy** [comment]
To close?

**Comment by asvetlov** [comment]
Fixed by #205
