### ISSUE TITLE
Can't keep the session.

### ISSUE THREAD

**Issue by HolynnChen** [aio-libs/aiohttp-session#291]
when you use the
```python3
session=await get_session(request)
```
it will raise
```python3
Cannot decrypt cookie value, create a new fresh session
```
What happend?

**Comment by panagiks** [comment]
Hi @HolynnChen ,

A wild guess is that you are using a randomly generated (i.e. copy-paste from the example). This means that every time you re-start your application, a new key will be generated, which of course cannot decrypt the cookie data that was encrypted by the previous key.

To be more clear this line:

```py
fernet_key = fernet.Fernet.generate_key()
```

Is to demonstrate how you should generate keys. If this line exists in your code (and you don't use a single key, say by configuration) you will see the above error.

And to make a little 'steps to reproduce' path:

Empty browser (or Api tester) cookies => start your application => visit application and acquire session => stop your application => start your application again => revisit your application using the session acquired earlier

If the above causes the exception to be raised on the last step it means that you are generating a new key at each server restart.

Hope it helps :)

**Comment by HolynnChen** [comment]
@panagiks Thanks a lot:) yeah this error due to the random fernet_key, i change my code and fix it.

**Comment by panagiks** [comment]
Glad to be of assistance :)

**Comment by namewhat** [comment]
@HolynnChen 
请问你是怎么解决的？fernet_key = fernet.Fernet.generate_key()替换成自己固定的secret_key?

**Comment by asvetlov** [comment]
Please use English.

**Comment by namewhat** [comment]
> Please use English.

Oh, sorry. I think that guy is a chinese, so reply with chinese. I fixed this issue too.
