### ISSUE TITLE
Can't retrieve value from session

### ISSUE THREAD

**Issue by cpwr** [aio-libs/aiohttp-session#292]
Hi,

Please, help to understand what I am doing wrong:

```
import os

from aiohttp import web
from aiohttp_session import setup
from aiohttp_session.cookie_storage import EncryptedCookieStorage

app = web.Application()
setup(app, EncryptedCookieStorage(os.getenv('SECRET_KEY')))

```
than I'm trying to set value to the session in my first endpoint that redirects me to another domain (to make authorization in third-party service). Consider this:
```
from aiohttp_session import get_session, new_session

async def authorize(request):
        origin = request.headers.get('Origin')
        session = await new_session(request)
        session['origin'] = origin
        ... # some code that makes redirect
```

And then, returning to my app after successful auth process I want to get the `origin` from a session:

```
async def return_to_origin(request):
    session = await get_session(request)
    return web.HTTPFound(f'https://{session["origin"])
```
Now I'm getting a traceback:

```
[2018-06-06 17:46:05 +0300] [33221] [ERROR] Error handling request
Traceback (most recent call last):
  File "/my_app/lib64/python3.6/site-packages/aiohttp/web_protocol.py", line 385, in start
    resp = await self._request_handler(request)
  File "/my_app/lib64/python3.6/site-packages/aiohttp/web_app.py", line 338, in _handle
    resp = await handler(request)
  File "/my_app/lib64/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/my_app/lib64/python3.6/site-packages/aiohttp_session/__init__.py", line 149, in factory
    response = await handler(request)
  File "/my_app/src/my_app/app/views.py", line 125, in return_to_origin
    return web.HTTPFound(f'https://{session["origin"]}')
  File "/my_app/lib64/python3.6/site-packages/aiohttp_session/__init__.py", line 89, in __getitem__
    return self._mapping[key]
KeyError: 'origin'
```

**Comment by panagiks** [comment]
Hi @cpwr ,

I suspect the issue could be on the `# some code that makes redirect`; could you please include that part of the code (removing the actual service you query of course) ?

Additionally could you verify that a cookie is actually returned when querying the endpoint hat leads to `authorize` (either by inspecting your browser's cookie storage after the request, or with an API tester)?

The above will somewhat help narrow down the possible scenarios.

**Comment by cpwr** [comment]
@panagiks , thank you for your response.
The redirecting code looks like this:
```
return web.json_response({
            "authorization_url": authorization_url,
        }, headers=prepare_cors_headers(origin))

```
this URL is passed then to frontend that makes redirect with `window.location.href = response.data["authorization_url"]`. May this be a problem?

When getting a response, I can see a 

`Set-Cookie: AIOHTTP_SESSION="gAAAAABbGNZClwtCRAoANTgwcx2ADDPKBon5NcLp_l40oJ1h1o4Vf2nYfGkuos6JxOB72-D4dVMYpr4nebYmQqSDQS_0OO24N8g50d5FF0Tx5e1aseakjWI1bYnk5q-99XSzVdnA70L-HzWJWEpMZcsDh1Gc9UumL553wCHzP5tGCeKgWEBVDUY="; HttpOnly; Path=/`

in response headers.

When I was redirected on an auth service, I don't have any cookies with name `origin` set, I just have tested.

**Comment by panagiks** [comment]
Hey! Sorry for the delay,

* (Encrypted)CookieStorage should measure up just fine against Redis so I don't think that changes the logic all that much
* The cookie seems to be successfully set (not sure about its contents though)
* You won't see a cookie named 'origin'; the only cookie that will be set is `AIOHTTP_SESSION` what you see on the right hand side of that `=` is an encrypted mapping (dictionary) with the data you saved in the session
* The redirection shouldn't be an issue

Given the above notes, unfortunately I'm kind of blind here (in the sense that I don't see anything wrong the code you shared and that the cookie seems to be actually set).

I will try to reproduce the issue and let you know what I've found (hopefully within the following week).

**Comment by cpwr** [comment]
Ok, I've tried to use Redis as a storage and I've got the same result:

```
import os
import logging
import aioredis

from aiohttp import web
from aiohttp_session import setup
from aiohttp_session.redis_storage import RedisStorage
from aiohttp_swagger import setup_swagger

from app.routes import add_handlers

log = logging.getLogger(__name__)


async def init_web_app():

    app = web.Application(debug=get_debug_state())

    if app.debug:
        log.warning('App started in DEBUG mode!!!')

    app['start_time'] = datetime.now()
    app.on_startup.append(create_redis_pool)
    app.on_cleanup.append(dispose_redis_pool)

    add_handlers(app)
    setup_swagger(app, swagger_url='/docs')
    return app


async def create_redis_pool(app):
    log.info('Creating Redis pool...')
    app["redis"] = await aioredis.create_redis_pool(
        f'redis://{os.getenv("REDIS_HOST", "redis")}',
        db=int(os.getenv("REDIS_DB", 0)),
        loop=app.loop,
    )
    setup_sessions(app, app["redis"])


async def dispose_redis_pool(app):
    log.info('Starting DB...')
    app["redis"].close()
    await app["redis"].wait_closed()


def setup_sessions(app, pool):
    storage = RedisStorage(pool)
    setup(app, storage)
    log.info('Sessions set up.')
```
Here are my endpoints:
```
from aiohttp_session import get_session, new_session

async def authorize(request):
    ...some logic

    origin = request.headers.get('Origin')

    if origin and authorization_url:
        session = await new_session(request)
        session['origin'] = origin
        return web.json_response({
            "authorization_url": authorization_url,
        }, headers=prepare_cors_headers(origin))

    log.error('"Origin" header is not correct')
    return web.json_response({'error': 'Headers are not correct'})
```
and another one, where I am trying to use the saved value:
```
async def redirect(request):
    session = await get_session(request)
    origin = session['origin']
    log.debug("Redirecting to origin: %s", origin)
    return web.HTTPFound(f'https://{origin}')
```
And now the error is:

```
Traceback (most recent call last):
  File "/my_app/lib64/python3.6/site-packages/aiohttp/web_protocol.py", line 385, in start
    resp = await self._request_handler(request)
  File "/my_app/lib64/python3.6/site-packages/aiohttp/web_app.py", line 338, in _handle
    resp = await handler(request)
  File "/my_app/lib64/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/my_app/lib64/python3.6/site-packages/aiohttp_session/__init__.py", line 149, in factory
    response = await handler(request)
  File "/my_app/src/app/views.py", line 127, in redirect
    origin = session['origin']
  File "/my_app/lib64/python3.6/site-packages/aiohttp_session/__init__.py", line 89, in __getitem__
    return self._mapping[key]
KeyError: 'origin'
```
Obviously, I am doing something wrong but I can't get, what exactly. Please, help

**Comment by Redict** [comment]
You gotta do:
```python
storage = EncryptedCookieStorage(os.getenv('SECRET_KEY'))
setup(app, storage)
```
That because of Storage initialization and Python one-line magic

**Comment by cpwr** [comment]
@Redict but the session var is created in a browser, are you sure?

**Comment by panagiks** [comment]
Hi @cpwr sorry for the delay. Could you make anI addition to your code (for debugging purposes)?

More specifically:

in `redirect` view function, after using get_session log the session.new attribute.

I'm suspecting that for some reason the cookie is not retained in your frontend.

If `session.new` is `True` but a cookie is set when you try with an API tester it means that something doesn't persist correctly.

**Comment by panagiks** [comment]
@Redict 's concern shouldn't affect the behavior for two reasons:

* As you can see in [aiohttp AppRunner](https://github.com/aio-libs/aiohttp/blob/8a0b25908a24d7d6e2dd50b319d72cae85847165/aiohttp/web_runner.py#L275) middlewares are frozen *after* the on_startup signal
* If your code tried to append (what `setup` does) to a FrozenList (i.e. middlewares that have been frozen) you would get an Exception raised during your apps initialization

**Comment by cpwr** [comment]
Hi @panagiks
It took too long to debug and I've solved my problem just by using Redis. Sadly, I don't have enough time to revert it back and test what you're suggesting. So if that's all, we can close this issue and forget about it

Thanks
