### ISSUE TITLE
Could not find a version that satisfies the requirement aiohttp>=3.0.1

### ISSUE THREAD

**Issue by AYeropudov** [aio-libs/aiohttp-session#305]
need to be updated requirements
from the cloned repo installation will ok

**Comment by gyermolenko** [comment]
yeah, `setup.py` has `python_requires=">=3.5",` and `aiohttp>=3.0.1` is for `>=3.5.3`

**Comment by panagiks** [comment]
Hi @AYeropudov ,

Could you please add the output of the pip install command that presented you with this error.

Thank you.
