### ISSUE TITLE
Useful to switch JSON libraries?

### ISSUE THREAD

**Issue by enugentdt** [aio-libs/aiohttp-session#310]
Hello, developers

I had a sort of discussion question. For storing sessions in Redis, for example, rather than locally or in cookies, one of the main reasons would be speed, along with the ability for multiple servers to share a user's session. I know I am personally interested in the speed of it.

Would there be any validity of changing the internal JSON library to be something faster, such as [ujson](https://github.com/esnme/ultrajson/)? It would be a very simple PR and I would be more than happy to do it (I plan on using the library internally, and to see how it holds up in a production environment). Or, if there is a desire to minimize the number of dependencies, maybe something in the documentation would help?

Thanks for your time!

**Comment by asvetlov** [comment]
Did you compare it?
Not `json` vs `ujson` but full stack: aiohttp+aiohttp_session+json/usjon?

**Comment by asvetlov** [comment]
Close after a long inactivity period
