### ISSUE TITLE
Travis CI doesn't see the repo commits/PRs

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-session#327]
Looks like the integration is broken.

@webknjaz I very appreciate if you find a time for this issue.

**Comment by webknjaz** [comment]
Any details in particular?

Normally this happens when some job was in queue and someone force pushes the branch, which renders the commits inaccessible, and then when the job finally gets executed there's nothing to fetch from GitHub and it fails.

**Comment by asvetlov** [comment]
#323 and #324 are dangling PRs.
I've merged #326 -- didn't see Travis builds neither on PR not on marge-to-master commit

**Comment by webknjaz** [comment]
Oh, I see. https://travis-ci.com/aio-libs/aiohttp-session/requests:
> Could not parse .travis.yml

**Comment by asvetlov** [comment]
My fault. I'll fix this

**Comment by asvetlov** [comment]
c0ab6ce

**Comment by asvetlov** [comment]
Fixed
