### ISSUE TITLE
[TODO] Fix `async with` blocks for Python 3.7+ compat

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp-session#329]

**Comment by panagiks** [comment]
Hi @webknjaz . 

Do you mean replacing `with await` blocks [like this](https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/redis_storage.py#L47) with `async with` ?

If so you can assign this to me and I'll give it a go in the weekend (or earlier) :)

**Comment by asvetlov** [comment]
No so easy.
Looks like aioredis should be fixed first.

**Comment by asvetlov** [comment]
https://github.com/aio-libs/aioredis/issues/425
