### ISSUE TITLE
Difference from jwt

### ISSUE THREAD

**Issue by giovanni5** [aio-libs/aiohttp-session#402]
The cookie provided by aiohttp-session is different from a json web token? Can i read the payload from client, for example vue js?
Thanks.

**Comment by asvetlov** [comment]
Consider it as opaque structure available on server side only.
If you need JWT you probably have to derive from `AbstractStorage` and implement JWT-aware version. 

Not sure if accessing cookies from JavaScript is a good idea, secure server should use HttpOnly flag for cookie to prevent XSS attack. Quick googling points on a good article: https://medium.com/@jcbaey/authentication-in-spa-reactjs-and-vuejs-the-right-way-e4a9ac5cd9a3

**Comment by giovanni5** [comment]
thank you, this article is interesting. So the client needs to call the server to checks if the user is authenticated or not.

> If you are using a single httpOnly cookie, the SPA should make an API call, for instance, //backend/api/me to know who is the current user and get an unauthorized error if the authentication cookie (containing the JWT) is missing or invalid.

**Comment by asvetlov** [comment]
Strictly speaking the code should call server even for non-browser usage.
You can use asymmetric cryptography to check the JWT sign but still need to ask the server if the user was blocked or banned (JWT has only time-based expiration obviously).
