### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-session#403]
The issue is relatively easy.

Does anybody want to be a champion?

**Comment by panagiks** [comment]
I could take it (ETA this Sunday). Do you prefer inline or *.pyi stubs ?

**Comment by asvetlov** [comment]
The inline is more robust.
Also would be nice to add annotations to tests (the test suite is not huge).
It is a little tedious but in the end you'll get a checker that library code is called with correct types; arguments types match declared annotations.
The mypy checker should be executed in strict mode (`mypy --strict aiohttp_session tests`) to enforce the best practices.
