### ISSUE TITLE
Connection <RedisConnection [db:0]> has pending commands, closing it.

### ISSUE THREAD

**Issue by bitnom** [aio-libs/aiohttp-session#438]
This happens with this package when I run a stress test of `./wrk -t12 -c400 -d30s http://localhost`

Output doesn't show me line number. Must be in the module somewhere. Related threads:

https://github.com/aio-libs/aioredis/issues/122

https://github.com/django/channels_redis/issues/71

**Comment by Dreamsorcerer** [comment]
A simple example app that can reproduce the issue would be good.

Or, a PR if you've managed to fix it. The redis code in this library appears to be just 2 calls: `await self._redis.get(...)` and `await self._redis.set(...)`.
