### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by TensorTom** [aio-libs/aiohttp-session#439]
I am using the Redis implement. Do we have any garbage collection? Is there a method that can clear a user's session so it is cleared from Redis, freeing resources? How should that be handled? Or just set pointers to null?

**Comment by panagiks** [comment]
Hello @TensorTom ,

From a first look in the `Session` API there is an `invalidate` method that empties the session data ([ref](https://github.com/aio-libs/aiohttp-session/blob/136da7df3a47e9cb88934a45a020842cb005839d/aiohttp_session/__init__.py#L72-L74)). But the `RedisStorage`'s `save_session` method just persists the changed session data (so `{}` as string) to Redis and doesn't handle deletion in that case ([ref](https://github.com/aio-libs/aiohttp-session/blob/136da7df3a47e9cb88934a45a020842cb005839d/aiohttp_session/redis_storage.py#L75-L79)).

I haven't yet looked into the other `Storage` implementations to see what the expected / consistent behavior would be in this case. But IMO it would make sense to have the option to enable deletion instead, although I wouldn't make it the default, as maintaining invalidated sessions until their 'natural' expiry has a few usecases (namely security logging). Having said that, the change to support this doesn't seem that complicated (`RedisStorage.save_session` logic can be 'cleaned-up' a bit to avoid the if-tree and then a decision can be added to `set` or `delete` the key).

As a temporary solution (if the lack of session key cleanup is pressing issue for you) you could do something like the following:

```py
class MyRedisStorage(RedisStorage):
    async def save_session(self, request, response, session):
        key = session.identity
        if key is None:
            key = self._key_factory()
            self.save_cookie(response, key,
                             max_age=session.max_age)
        else:
            if session.empty:
                self.save_cookie(response, '',
                                 max_age=session.max_age)
            else:
                key = str(key)
                self.save_cookie(response, key,
                                 max_age=session.max_age)
        if session.empty:
            await conn.delete(self.cookie_name + '_' + key)
            return
        data = self._encoder(self._get_session_data(session))
        with await self._redis as conn:
            max_age = session.max_age
            expire = max_age if max_age is not None else 0
            await conn.set(self.cookie_name + '_' + key, data, expire=expire)
```

Again the above is really just copy-paste of the current code with the addition of an if-clause to delete the key and I have not actually tested it (let alone thoroughly :D ) so please test that it covers your usecase and adapt the example to your needs before using it in production code :) 

That's all I have for now unfortunately, I'll try to see how the proposed behavior fits with the current behavior of other Storage Classes and try to prepare an MR with a solution that supports both options but I do not have an ETA on that.
