### ISSUE TITLE
Test support for local memcached and redis servers

### ISSUE THREAD

**Issue by jayvdb** [aio-libs/aiohttp-session#518]
aioredis, aiomcache and aiocache test rigs all support pytest arguments for specifying to use a local server for memcached/redis.  This is helpful for testing on isolated distro builds, where docker is not able to pull images, but the distro packages for those services is easily installable.

**Comment by asvetlov** [comment]
Please feel free to make a Pull Request.
This mode should be optional, the dockerized server is handy when Docker is available.

**Comment by Dreamsorcerer** [comment]
Think we're using a local one now, and the docker one is broken.
