### ISSUE TITLE
aiohttp 3.7 samesite flag voor cookies cant be set

### ISSUE THREAD

**Issue by Sult** [aio-libs/aiohttp-session#536]
since aiohttp 3.7, there is now an option to use samesite flag (which defaults to None) for cookies.
However aiohttp-session has no way to pass this

**Comment by Dreamsorcerer** [comment]
Already fixed: https://github.com/aio-libs/aiohttp-session/pull/449

Once @asvetlov unblocks me on https://github.com/aio-libs/aiohttp-session/pull/527 I'll get it merged.

**Comment by Dreamsorcerer** [comment]
This needs aiohttp 3.7+, but due to a bug in 3.7 that causes problems with aiohttp-session, I'll have to push this back till the 3.8 release is out.
