### ISSUE TITLE
sessions not saved with HTTPExceptions

### ISSUE THREAD

**Issue by ojii** [aio-libs/aiohttp-session#548]
I'm not sure if this is an issue with how I use aiohttp/aiohttp-session, aiohttp-session itself or aiohttp, so let me know if I should report it somewhere else.

I'm trying to set a new session using EncryptedCookieStorage and then redirect the user to a different page using `aiohttp.web.HTTPFound("/url/")`. However, in that case, the new session is lots. If I instead manually create the redirect using `aiohttp.web.Response(status=302, headers={"Location": "/url/"})` it works. 

I've created a small repo with a test that shows that the `HTTPFound` based version doesn't work, while the `Response` one does. You can access it at https://github.com/ojii/aiohttp-session-httpfound-issue

**Comment by Dreamsorcerer** [comment]
Known issue with aiohttp 3.7. You can downgrade to 3.6, and it's already fixed in the upcoming 3.8.
Or, as a temporary workaround you can `return` the exception rather than `raise` it.

**Comment by havardgulldahl** [comment]
For anyone else coming here from a web search: This also happens with `HttpSeeOther` (and other redirects, perhaps?), but replacing `raise` with `return` fixed this at once. Thanks, @Dreamsorcerer!
