### ISSUE TITLE
Can't retrieve value from session after raise HTTPFound 

### ISSUE THREAD

**Issue by carleshf** [aio-libs/aiohttp-session#580]
So, I am implementing open-id login and I assign the state to the session so I can redirect to the web portal for user authentication. This will redirect to the function and get the access token. I do it as:

    async def do_login(request, next_url):
        request_session = await get_session(request)
        code = request.query.get('code')
        LOG.debug('code: %s', code)
        if code is None:
            LOG.debug('We must have a code')
            state = str(uuid.uuid4())
            params = urlencode({ 'response_type': 'code',
                                'client_id': conf.kc_client_id,
                                'scope': conf.kc_scope,
                                'state': state,
                                'redirect_uri': conf.kc_redirect_uri })
            url = conf.kc_authorize if conf.kc_authorize.endswith('?') else (conf.kc_authorize + '?')
            url += params
            request_session['oidc_state'] = state
            LOG.debug('No code: Redirecting to URL: %s', url)
            raise HTTPFound(url)

        stored_state = request_session.get('oidc_state')
        LOG.debug('stored_state: %s', stored_state)
        state = request.query.get('state')
        LOG.debug('state: %s', state)
        if not state or stored_state != state:
            LOG.error('invalid state | %s =/= %s', stored_state, state)
            raise HTTPBadRequest(reason="Invalid state")

        # We have a code and a state
        LOG.debug('Code: %s', code)

        params = { 
            'grant_type': 'authorization_code',
            'code': code,
            'redirect_uri': conf.kc_redirect_uri
        }
        LOG.debug( 'Post Request %r', params)
        data = {}
        async with ClientSession() as session:
            LOG.debug('Contacting %s', conf.kc_access_token)
            async with session.post(conf.kc_access_token,
                                    headers={ 'Accept': 'application/json' },
                                    auth=BasicAuth(conf.kc_client_id,password=conf.kc_client_secret),
                                    data=FormData(params, charset='UTF-8')
            ) as resp:
                if resp.status > 200:
                    LOG.error( 'Error when getting the access token: %r', resp)
                    raise HTTPBadRequest(reason='Invalid response for access token.')
                data = await resp.json()

        # extract access token
        access_token = data.get('access_token')
        if not access_token: 
            LOG.error( 'Error when getting the access token')
            raise HTTPBadRequest(reason='Failed to obtain OAuth access token.')

        LOG.debug('All good, we got an access token')
        # LOG.debug('Token: %s', access_token)
        request_session['access_token'] = access_token

        # Finally, save userinfo and redirect
        await get_user_info_and_redirect(access_token, next_url, request_session)

The issue is that the `raise HTTPFound(url)` (line: 17) opens the web portal for user authentication and then the `raise HTTPBadRequest(reason="Invalid state")` (line: 25) is run because `stored_state` is `None`, although it was set before (lines 15 and 19). From [here](https://github.com/aio-libs/aiohttp-session/issues/548) I tried to change the `raise` to `return` (line: 17) but then all stops working.

**Comment by Dreamsorcerer** [comment]
> From [here](https://github.com/aio-libs/aiohttp-session/issues/548) I tried to change the `raise` to `return` (line: 17) but then all stops working.

Did you also try downgrading to aiohttp 3.6? If it's the same issue, then that will solve the problem. If it's not solved, then it must be a different issue.

**Comment by smoothjump** [comment]
I faced the same issue here, downgrading solved this issue, thanks.  I also wonder if there are any other workaround here.

**Comment by Dreamsorcerer** [comment]
Using 'return' is the workaround... Just stick to aiohttp 3.6 until 3.8 is released (which fixes the issue).
