### ISSUE TITLE
Bump aioredis version to +2.x

### ISSUE THREAD

**Issue by phenobarbital** [aio-libs/aiohttp-session#605]
Hi!

there is a plan to work in a version with aioredis 2.0 support?, I made some local changes in the redis_storage (mostly removing the "create_pool" and alternately using the aioredis.ConnectionPool) and the library work without issues.

there is such a plan or I can send a PR with my changes?

**Comment by Dreamsorcerer** [comment]
Duplicate of #528 

Yes, PRs would be welcome.
