### ISSUE TITLE
Update documentation for the redis module

### ISSUE THREAD

**Issue by amenezes** [aio-libs/aiohttp-session#760]
@Dreamsorcerer,

Now that **aiohttp-session** uses `redis` as dependency it's necessary update project documentation. Could I submit a PR with the changes?

Another observation is that `demo/redis_storage.py` fail because:

- [import aioredis](https://github.com/aio-libs/aiohttp-session/blob/master/demo/redis_storage.py#L4)

```bash
ModuleNotFoundError: No module named 'aioredis'
```

- [parameter `timeout=1`](https://github.com/aio-libs/aiohttp-session/blob/master/demo/redis_storage.py#L23)

```bash
...
    return self.connection_class(**self.connection_kwargs)
TypeError: Connection.__init__() got an unexpected keyword argument 'timeout'
```

**Comment by Dreamsorcerer** [comment]
Yes please.

Looks like we didn't have typing on aioredis, otherwise mypy would have caught the demo: https://github.com/aio-libs/aiohttp-session/blob/master/.mypy.ini#L30

So, a little more than just the docs, but probably need to grep the entire repo for `aioredis` and check each one.
