### ISSUE TITLE
With max_age set, cookies expire immediately on IE11 or Edge

### ISSUE THREAD

**Issue by dannyclark** [aio-libs/aiohttp-session#81]
With max_age set, expiry is calculated using `time.gmtime(time.monotonic() + max_age)`

I don't think `time.monotonic()` reliably gives number of seconds since the epoch, so on my server, expiry is calculated to a 1970 date e.g. `expires=Sat, 31-Jan-1970 04:52:49 GMT` and a user using IE or Edge never gets a cookie. Interestingly Firefox and Chrome ignore the old expires value and the cookie works (I suspect it will never expire).

It seems to work for me to use `time.time()` in place of `time.monotonic()` but I wasn't clear on the intention of using the monotonic clock here?

**Comment by asvetlov** [comment]
`asyncio` uses monotonic timer, I just borrowed it without careful thinking.
Yes, in this particular case (calculating absolute time, not relative to current time) we should use `time.time()`.

Very nice catch, BTW.
Thank you a lot!

**Comment by asvetlov** [comment]
Released as 0.8.0
