### ISSUE TITLE
Why is SimpleCookieStorage insecure?

### ISSUE THREAD

**Issue by yanxurui** [aio-libs/aiohttp-session#842]
I am trying to understand why `SimpleCookieStorage` is not secure and should be never be used in production. Any hint would be appreciated.

**Comment by Dreamsorcerer** [comment]
Feel free to add some information to the documentation.

The class simply dumps the session data into a cookie as plain text. This makes it easy for development, as you can just look at the cookie in your browser to see what the session contains. But, anybody can put anything in there, so the data can't be trusted (e.g. If you put a user ID in the session, you can just change the ID and identify as any other user without authentication).

The recommend cookie storage encrypts the contents of the session before saving in a cookie. That means the contents can't be manipulated without the key, which should only exist on the server. It could potentially hide sensitive data in the session from the user too.

**Comment by Dreamsorcerer** [comment]
See:
https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/__init__.py#L352
vs.
https://github.com/aio-libs/aiohttp-session/blob/master/aiohttp_session/cookie_storage.py#L76

**Comment by yanxurui** [comment]
Thanks @Dreamsorcerer. I understand the encrypted one can prevent from tampering while it does not help if the cookie was stolen.

**Comment by Dreamsorcerer** [comment]
As mentioned in the other thread, no storage implementation helps if the session details are stolen. The developer needs to implement a feature to allow revoking sessions to provide any mitigation, which is not really related to the storage mechanism.
