### ISSUE TITLE
Clarify the Redis key inside the docs

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiohttp-session#85]
Actually the doc doesn't specify that they key inside Redis would be: AIOHTTP_SESSION_valueofthecookie

**Comment by asvetlov** [comment]
Who need this info?
Anyway, PR is welcome!

**Comment by barrachri** [comment]
Well my use case is probably "strange" but I needed to check the validity of the session outside aiohttp.

I will send a PR !

**Comment by jettify** [comment]
Resolved via https://github.com/aio-libs/aiohttp-session/pull/94
